<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GestorAlquiler.Domain</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Entities\Cliente.cs" />
    <Compile Include="Interfaces\IClienteRepository.cs" />
  </ItemGroup>

</Project>
